version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: realestate_db
      POSTGRES_USER: realestate_user
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U realestate_user -d realestate_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://realestate_user:password123@postgres:5432/realestate_db
      - REDIS_URL=redis://redis:6379
      - NEWS_API_KEY=${NEWS_API_KEY}
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./logs:/app/logs
    command: python -m uvicorn real_estate_rag_system:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
  redis_data:
